### ISSUE TITLE
Singular Filled Icon

### ISSUE THREAD

**Issue by jasonwbullok** [dreyescat/bootstrap-rating#10]
Would it be possible to make the selected rating be the only filled icon?

Something along this line:

![ratings-example](https://cloud.githubusercontent.com/assets/10633657/6516197/fb61e5a6-c35d-11e4-82f7-37d7b2d016ac.jpg)

**Comment by dreyescat** [comment]
Thanks for your suggestion @jasonwbullok!

I have added a new attribute (filled-selected) to have more control over how the selected symbol is filled. With this new attribute you can customize the rating control to show a single filled icon like this:

    <input type="hidden" class="rating" data-filled="glyphicon glyphicon-heart-empty" data-filled-selected="glyphicon glyphicon-heart" data-empty="glyphicon glyphicon-heart-empty"/>

Or programmatically:

    $('input').rating({
      filled: 'glyphicon glyphicon-heart-empty',
      filledSelected: 'glyphicon glyphicon-heart',
      empty: 'glyphicon glyphicon-heart-empty'
    });

Hope it helps.
