### ISSUE TITLE
Readonly rating with a fractional value

### ISSUE THREAD

**Issue by marjanbajc** [dreyescat/bootstrap-rating#12]
Hi, 

very nice plugin. Thanks for sharing.

in the demo under Readonly rating with a fractional value, the value is 2.5 which should fill 2.5 stars but it only fills 2.

Is it possible to show 2.5 stars filled?

Thank you.

**Comment by dreyescat** [comment]
Thanks for reporting this bug @marjanbajc!

Yep, it should work now in version 1.1.1. It was a regression I introduced in version 1.0.4.

**Comment by marjanbajc** [comment]
Very nice, It works. Thanks. :)
