### ISSUE TITLE
Programatically set the value

### ISSUE THREAD

**Issue by therocode** [dreyescat/bootstrap-rating#13]
Hello!

Is it at all possible to set the value of a bootstrap-rating displayer programatically?
I noticed another issue posted about it but it was subsequently closed without any information on a solution.
Regards

**Comment by dreyescat** [comment]
First of all, thanks @therocode for the feedback.

I saw that issue that you mention. Yes, it was created and immediately closed afterwards by the same user. So I just ignored the issue.

Following your suggestion, I think I will add some explicit method to the plugin to set the value programmatically. But in the meantime, you can accomplish more or less the same effect simulating the *change* event on the associated *input*. Something like this:

```html
<input type="hidden" class="rating" id="programmatically-rating">
```
```javascript
$('#programmatically-rating').val(3).change();
```

Anyway, I am planning to add that method to explicitly set the value programmatically.

**Comment by therocode** [comment]
Thanks for the reply!

It's nice to see that this could end up an improvement for the library. IMHO adding such a function would make sense since it's not a farfetched thing to want to do.

The meanwhile-solution works well! Thanks for that, and for the library itself!

I'll leave this open in case you want to keep it until said feature is implemented. Otherwise, feel free to close it.

**Comment by dreyescat** [comment]
Done!

Added a [rate setter/getter](https://github.com/dreyescat/bootstrap-rating#rate).
