### ISSUE TITLE
Size of Stars

### ISSUE THREAD

**Issue by BrewDawg** [dreyescat/bootstrap-rating#15]
How can we change the size of the glyph icons, I've can't figure out how to make them larger ...

**Comment by dreyescat** [comment]
What I would do is to create a new CSS style with a larger `font-size` and add it to the `filled` and `empty`  list of classes, along with the glyph classes.

For example:
```css
<style>
  .large-rating {
    font-size: 2em;
  }
</style>
```

```html
<input type="hidden" class="rating" data-filled="glyphicon glyphicon-heart large-rating" data-empty="glyphicon glyphicon-heart-empty large-rating"/>
```

Let me know if it is not clear enough. I will try to add an example to the demo page later.

**Comment by dreyescat** [comment]
Just added the example I promised. It has custom size and color. Check [demo](http://dreyescat.github.io/bootstrap-rating/) page.
