### ISSUE TITLE
Data fraction go wrong for RTL wrappers

### ISSUE THREAD

**Issue by ihabovich** [dreyescat/bootstrap-rating#16]
Hello,
I just noticed while implementing the code that data fraction is some how reversed direction on.Hover:

```html
<input type="hidden" class="rating" data-fractions="2" value="4.5"/>
```
I get to fix the value="4.5", since the half star visible on page load was also reversed by changing this snippet .js (left:0 => right:0):
```javascript
overflow:"hidden",right:0,width:0
```
However, didn`t get to fix the half star hover issue.

**Comment by dreyescat** [comment]
Thanks for your feedback! You pointed me to the solution. I just had to think as if the `left` was the `right` position :).

I have added support for fractional right-to-left symbols. So in version [1.3.1](https://github.com/dreyescat/bootstrap-rating/releases/tag/v1.3.1) it should work.

**Comment by ihabovich** [comment]
Thanks for the fix.
