### ISSUE TITLE
Cursor type is text when using FireFox

### ISSUE THREAD

**Issue by robertlabrie** [dreyescat/bootstrap-rating#21]
FF43 Win10 x64 - the cursor when hovering over the glyphs is the text select cursor instead of the default cursor.

PS: Thanks for this. I made my own (https://github.com/robertlabrie/bootstrap-star-rating), yours is better, please take a look at the cursor when you get a chance.

Thanks,
Rob

**Comment by dreyescat** [comment]
Thanks for the feedback @robertlabrie!

Yep. It seems that Firefox `auto` pointer determines that the rating is text. Then it shows this I-beam cursor.

I have forced the pointer to be always the `default` (usually an arrow). Now all browser should consistently show the same `default` cursor.

**Comment by dreyescat** [comment]
By the way. In case you need to customize the cursor you can do it creating a class with the desired `cursor`:
```css
.custom-cursor {
  cursor: pointer;
}
```
and then add this class to the list of classes for the `data-filled` and `data-empty` attributes:
```html
<input type="hidden" class="rating" data-filled="fa fa-star fa-3x custom-cursor" data-empty="fa fa-star-o fa-3x custom-cursor" />
```
Check the [example](https://jsfiddle.net/dreyescat/z4ddr6zr/).

**Comment by robertlabrie** [comment]
Thanks for your help, and the fast turn around. Any idea when the fixed version might be on out cdnjs?

**Comment by dreyescat** [comment]
According to the cdnjs documentation it [should not take more than 12 hours](https://github.com/cdnjs/cdnjs/blob/008848003b936d67b1c4de22954f922c0041440f/documents/autoupdate.md).

**Comment by dreyescat** [comment]
BTW, I just checked an it is already there. :clap: for cdnjs!
