### ISSUE TITLE
about setting initial value by jQuery

### ISSUE THREAD

**Issue by ensean** [dreyescat/bootstrap-rating#22]
Hi, I tried to set the initial value by jQuery, but I find that the initial value can not be shown unless the mouse flies over it. I also tried to fire the hover event on the rating input, but it doesn't work either... 

```html```
<input id="evalscore"  style="margin-left: 10px" type="hidden" class="rating"  data-readonly/>

```javascript```
 $("#evalscore").val(res.evalInfo.score)

**Comment by dreyescat** [comment]
Hi @ensean,

Check the [`rate`](https://github.com/dreyescat/bootstrap-rating#rate) method to see how you can programmatically set the rating value.

Applied to your case it should be something like this:

```javascript
$("#evalscore").rating('rate', res.evalInfo.score)
```

Hope it helps!

**Comment by ensean** [comment]
@dreyescat It works! I should have read the readme.md more carefully. Thanks a lot for your response.
