### ISSUE TITLE
How to unselect the selected first star

### ISSUE THREAD

**Issue by dm7777** [dreyescat/bootstrap-rating#27]
Hi 
I have implemented your plugin in my app. However how do you unselect the first star after it has been selected

You can unselect the other starts by clicking on the previous star but how do you unselect the first star after it has been selected.

Many thanks in advance

**Comment by dreyescat** [comment]
I have released a new version [1.4.0](https://github.com/dreyescat/bootstrap-rating/releases/tag/v1.4.0) that allows programmatically reset the rate. Check the [docs](https://github.com/dreyescat/bootstrap-rating#rate) or the [demo](http://dreyescat.github.io/bootstrap-rating/) more info.
