### ISSUE TITLE
Value not receiving angular variables sometimes

### ISSUE THREAD

**Issue by cheriyankmaman** [dreyescat/bootstrap-rating#28]
`<input type="hidden" class="rating" data-fractions="10" id="ho_rating" value='{{rating}}' data-readonly data-filled="fa fa-star fa-2x" data-empty="fa fa-star-o fa-2x" />`

the above code not showing stars.

**Comment by dreyescat** [comment]
I don't know Angular but I think you are *mixing* two different worlds. Angular uses a declarative way of building interfaces while jQuery is imperative. You are trying to use two way data binding for `value`. However, in jQuery this attribute is just used as initialization.

Try google *how to integrate jquery plugins in angular*. I think you need some extra work. Probably you will have to create an Angular wrapper if you want to reuse this component with Angular in this way.
