### ISSUE TITLE
$('.c-rating').rating('rate', ''); will not clear rating

### ISSUE THREAD

**Issue by macpatel** [dreyescat/bootstrap-rating#31]
use $('.c-rating').rating('rate', 0); to clear the rating. Thanks! please update end of the docs.

Thanks!

**Comment by dreyescat** [comment]
Hi @macpatel,

Which version are you using?

**Comment by dreyescat** [comment]
Check this [jsfiddle](https://jsfiddle.net/dreyescat/hg5a8c85/).

**Comment by macpatel** [comment]
Not a bug. My Bad. I guess i was using older version.
