### ISSUE TITLE
Cannot display 10 stars, shows all empty

### ISSUE THREAD

**Issue by deb0rian** [dreyescat/bootstrap-rating#7]
Using either:
> input type="hidden" class="rating" data-start="0" data-stop="10" readonly="readonly" value="10"
Or even:
> input type="hidden" class="rating" data-start="1" data-stop="10" readonly="readonly" value="10"

Displays empty stars.. No option for full rating.

Also, setting data-fractions="2" doesn't display value="9.5" properly.

I'm talking about setting manual values only.

**Comment by dreyescat** [comment]
Thanks for reporting the issue.

This issue was solved in #6. It was my fault that I forgot to update the minimized version appropriately.
Check again with the updated version and let me know if it doesn't fix the issue.
