### ISSUE TITLE
Problem with multiple ratings under iOS7

### ISSUE THREAD

**Issue by mittererr** [dreyescat/bootstrap-rating#8]
On my iPhone 4 I have a problem with multiple ratings. For example I can choose 3 stars for the first rating. When I try to select 4 stars in the next row, the selection from the first row is lost!?

Any Suggestions?

**Comment by dreyescat** [comment]
Thanks for reporting this issue.

It does not only affect a specific device or version of the operating system. Even not only a specific version of the browser. It seems that none of the iOS devices support *click* events. Instead [TouchEvents](https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent) should be used. So, I have added basic support for touch events.

Hope it helps.

**Comment by nwittstruck** [comment]
I'm still having this issue on iOS 10 - any idea how to fix this?

**Comment by BoussonNicolas** [comment]
I am having the same bug even on iOS 8
